# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import DhiGRPC_pb2 as DhiGRPC__pb2


class DhiGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/DhiGRPC/Ping',
                request_serializer=DhiGRPC__pb2.Echo.SerializeToString,
                response_deserializer=DhiGRPC__pb2.Echo.FromString,
                )


class DhiGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DhiGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=DhiGRPC__pb2.Echo.FromString,
                    response_serializer=DhiGRPC__pb2.Echo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DhiGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DhiGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DhiGRPC/Ping',
            DhiGRPC__pb2.Echo.SerializeToString,
            DhiGRPC__pb2.Echo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
